package enums;

public enum ConfigProperties {

	URL, BROWSER, OVERRIDEREPORTS, FAILEDSTEPSCREENSHOT, PASSEDSTEPSCREENSHOT, SKIPPEDSTEPSCREENSHOT, RETRYCHECK,
	RETRYCOUNT, RUNMODE, SELENIUMGRIDURL

}
